Repository apiman/apiman, pull requests merged in 2021-04, with the labels that each got.

#1108 build(deps): bump vert.x from 3.9.6 to 3.9.7
  pom.xml
Labels: dependency

#1115 build: add Maven wrapper
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: build

#1110 feat(common-logging): add support for jboss-logging
  common/logging/jboss-logging/pom.xml
  common/logging/jboss-logging/src/main/java/io/apiman/common/logging/jboss/JbossLoggerFactory.java
  common/logging/jboss-logging/src/main/java/io/apiman/common/logging/jboss/JbossLoggerImpl.java
  common/logging/pom.xml
Labels: enhancement

#1119 fix(distro-vertx): remove argument quotes breaking launch script
  distro/vertx/src/main/resources/overlay/apiman-gateway.sh
Labels: bug

#1117 build(deps): bump OkHttp from 2.4.0 to 2.7.5
  gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpConnectorFactory.java
  gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/ok/HttpURLConnectionImpl.java
  gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/components/jdbc/JdbcTestSuite.java
  gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/components/jdbc/SpecHelpers.java
  gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/components/jdbc/suitetests/CreateTableTest.java
  gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/components/jdbc/suitetests/QueryTest.java
  pom.xml
Labels: dependency

#1121 chore(es): allow optional use of Amazon open distro images
  common/es/src/main/java/io/apiman/common/es/util/EsConstants.java
  common/es/src/main/java/io/apiman/common/es/util/EsUtils.java
  common/es/src/main/resources-filtered/io/apiman/common/es/util/apiman-embedded-elastic.properties
  common/es/src/main/resources-filtered/io/apiman/common/es/util/apiman-es.properties
  gateway/test/src/test/java/io/apiman/gateway/test/junit/servlet/ServletGatewayTestServer.java
  gateway/test/src/test/java/io/apiman/gateway/test/junit/vertx3/Vertx3GatewayEsServerFactory.java
  manager/test/api/src/main/java/io/apiman/manager/test/server/ManagerApiTestServer.java
  manager/test/api/src/test/java/io/apiman/manager/test/es/EsMetricsAccessorTest.java
  pom.xml
  test/common/pom.xml
  test/common/src/main/java/io/apiman/test/common/es/EsTestUtil.java
Labels: enhancement

#1124 fix(gateway-vertx): fix proxy support in plugin resolver
  common/util/src/main/java/io/apiman/common/util/Basic.java
  gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPluginRegistry.java
  gateway/platforms/vertx3/vertx3/pom.xml
  gateway/platforms/vertx3/vertx3/src/main/generated/io/apiman/gateway/platforms/vertx3/common/config/InheritingHttpClientOptionsConverter.java
  gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/common/config/InheritingHttpClientOptions.java
  gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/common/config/VertxEngineConfig.java
  gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/engine/VertxPluginRegistry.java
  gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/engine/proxy/AbstractCredentials.java
  gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/engine/proxy/HttpProxy.java
  gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/engine/proxy/HttpProxySettings.java
  gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/engine/proxy/JavaSysPropsProxySettings.java
  gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/engine/proxy/SysPropsProxySelector.java
  gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/engine/proxy/UsernamePasswordCredentials.java
  gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/engine/VertxPluginRegistryTest.java
  gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/engine/proxy/JavaSysPropsProxySettingsTest.java
  pom.xml
Labels: bug

#1126 build(deps): bump version.org.eclipse.jetty from 9.4.39.v20210325 to 9.4.40.v20210413
  pom.xml
Labels: dependency

#1093 build: ensure Apiman can build under Java 16
  .github/workflows/verify.yaml
  gateway/engine/beans/pom.xml
  manager/api/beans/pom.xml
  manager/api/config/pom.xml
  manager/api/micro/pom.xml
  manager/api/war/tomcat8/pom.xml
  pom.xml
Labels: ci, dependency, java, refactor

#1142 build(deps): bump jaxws-ri from 2.3.3 to 2.3.4
  pom.xml
Labels: dependency

#1143 build(deps): remove unused commons-lang v2 dep
  common/config/pom.xml
  common/config/src/main/java/io/apiman/common/config/SystemPropertiesConfiguration.java
  pom.xml
Labels: dependency

#1145 refactor: remove OSGi
  common/auth/pom.xml
  common/config/pom.xml
  common/es/pom.xml
  common/net/pom.xml
  common/plugin/pom.xml
  common/servlet/pom.xml
  common/util/pom.xml
  gateway/api/rest-impl/pom.xml
  gateway/api/rest/pom.xml
  gateway/engine/beans/pom.xml
  gateway/engine/core/pom.xml
  gateway/engine/es/pom.xml
  gateway/engine/filesystem/pom.xml
  gateway/engine/hazelcast/pom.xml
  gateway/engine/ispn/pom.xml
  gateway/engine/jdbc/pom.xml
  gateway/engine/osgi/.gitignore
  gateway/engine/osgi/pom.xml
  gateway/engine/osgi/src/main/java/io/apiman/gateway/engine/osgi/policy/OSGIPolicyFactory.java
  gateway/engine/policies/pom.xml
  gateway/engine/pom.xml
  gateway/engine/redis/pom.xml
  gateway/engine/storage-common/pom.xml
  gateway/platforms/servlet/pom.xml
  manager/api/beans/pom.xml
  manager/api/config/pom.xml
  manager/api/core/pom.xml
  manager/api/es/pom.xml
  manager/api/exceptions/pom.xml
  manager/api/export-import/pom.xml
  manager/api/gateway/pom.xml
  manager/api/ispn/pom.xml
  manager/api/jdbc/pom.xml
  manager/api/jpa/pom.xml
  manager/api/micro/pom.xml
  manager/api/migrator/pom.xml
  manager/api/rest-impl/pom.xml
  manager/api/rest/pom.xml
  manager/api/security/pom.xml
  manager/api/war/pom.xml
  pom.xml
Labels: dependency, refactor

#1147 refactor: use parseInt instead of ctor/new Integer
  common/config/src/main/java/io/apiman/common/config/options/AbstractOptions.java
  gateway/engine/core/src/test/java/io/apiman/gateway/engine/impl/DefaultJdbcComponentTest.java
  gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsMetrics.java
  gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/PollCachingEsRegistry.java
  gateway/engine/jdbc/src/main/java/io/apiman/gateway/engine/jdbc/JdbcMetrics.java
  gateway/engine/jdbc/src/main/java/io/apiman/gateway/engine/jdbc/PollCachingJdbcRegistry.java
  gateway/engine/policies/src/test/java/io/apiman/gateway/engine/policies/TransferQuotaPolicyTest.java
  gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpApiConnection.java
  gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/common/config/VertxEngineConfig.java
  manager/api/gateway/src/main/java/io/apiman/manager/api/gateway/rest/GatewayClient.java
  manager/api/migrator/src/main/java/io/apiman/manager/api/migrator/VersionMigrators.java
  test/common/src/main/java/io/apiman/test/common/mock/EchoServlet.java
  test/common/src/main/java/io/apiman/test/common/util/TestUtil.java
  test/policies/src/main/java/io/apiman/test/policies/EchoBackEndApi.java
Labels: refactor

#1152 refactor: use new Apiman logging framework everywhere
  gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPolicyErrorWriter.java
  gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsMetrics.java
  gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsRegistry.java
  gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/PollCachingEsRegistry.java
  gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpApiConnection.java
Labels: refactor

#1118 refactor(es): revert waitUntil index refresh strategy. Use immediate.
  gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsRegistry.java
  manager/api/es/src/main/java/io/apiman/manager/api/es/EsStorage.java
Labels: bug

#1154 build(deps): bump maven-dependency-plugin, hibernate, ant
  pom.xml
Labels: dependency

#1156 build(deps): remove unused deps
  common/config/pom.xml
  common/es/pom.xml
  common/logging/log4j2/pom.xml
  common/logging/slf4j/pom.xml
  common/net/.gitignore
  common/net/pom.xml
  common/pom.xml
  gateway/engine/es/pom.xml
  gateway/engine/filesystem/pom.xml
  gateway/engine/hazelcast/pom.xml
  gateway/engine/influxdb/pom.xml
  gateway/engine/prometheus/pom.xml
  gateway/platforms/vertx3/vertx3-common/pom.xml
  gateway/platforms/vertx3/vertx3/pom.xml
  gateway/test/pom.xml
  manager/api/es/pom.xml
Labels: dependency

#1163 build(deps): bump junit 5, snakeyaml, guava, & apache ldap-api
  distro/ddl/pom.xml
  pom.xml
Labels: dependency
