Repository apiman/apiman, pull requests merged in 2021-06, with the labels that each got.

#1272 refactor: Create keycloak config based on realm file
  distro/data/src/main/resources/data/apiman-realm-for-keycloak.json
  distro/wildfly/src/main/assembly/overlay.xml
  distro/wildfly/src/main/docker/Dockerfile
  distro/wildfly/src/main/resources/overlay/standalone/configuration/standalone-apiman.xml
  distro/wildfly/src/main/resources/overlay/standalone/data/h2/keycloak.mv.db
Labels: enhancement

#1243 build(parent): force junit4 as default for surefire plugin
  manager/pom.xml
  parent/pom.xml
Labels: bug, build

#1207 feat: allow runtime logging level changes via REST API
  common/logging/core/pom.xml
  common/logging/core/src/main/java/io/apiman/common/logging/ApimanLoggerFactory.java
  common/logging/core/src/main/java/io/apiman/common/logging/IDelegateFactory.java
  common/logging/core/src/main/java/io/apiman/common/logging/LogLevel.java
  common/logging/core/src/main/java/io/apiman/common/logging/change/LogFileConfigManager.java
  common/logging/core/src/main/java/io/apiman/common/logging/change/LoggingChangeRequest.java
  common/logging/log4j2/src/main/java/io/apiman/common/logging/log4j2/Log4j2LoggerFactory.java
  distro/vertx/src/main/resources/overlay/log4j2.xml
  gateway/api/rest/pom.xml
  gateway/api/rest/src/main/java/io/apiman/gateway/api/rest/ISystemResource.java
  gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/ApiVerticle.java
  manager/api/rest/src/main/java/io/apiman/manager/api/rest/ISystemResource.java
Labels: enhancement

#1280 build(deps): bump mockito-core, icu4j, jandex, & hibernate
  parent/pom.xml
Labels: dependency, java

#1196 refactor(es): rework TLS configuration for Elasticsearch
  common/es/src/main/java/io/apiman/common/es/util/DefaultEsClientFactory.java
  common/es/src/main/java/io/apiman/common/es/util/EsConnectionPoller.java
Labels: bug

#1287 build(deps): bump elasticsearch, redisson, json-unit-assertj
  parent/pom.xml
Labels: dependency

#1291 Harmonize log4j2 configuration through the project
  distro/tomcat/src/main/resources/overlay/log4j2/conf/log4j2-tomcat.xml
  distro/vertx/src/main/resources/overlay/log4j2.xml
Labels: enhancement

#1299 fix(ui): fix spelling error in community.include
  manager/ui/war/plugins/api-manager/html/headers/community.include
Labels: bug

#1242 fix(manager-api): add API Definitions to export-import
  gateway/platforms/vertx3/vertx3/pom.xml
  gateway/platforms/war/micro/pom.xml
  gateway/platforms/war/tomcat8/api/pom.xml
  gateway/test/pom.xml
  manager/api/beans/src/main/java/io/apiman/manager/api/beans/apis/ApiDefinitionBean.java
  manager/api/beans/src/main/java/io/apiman/manager/api/beans/apis/ApiVersionBean.java
  manager/api/beans/src/test/java/io/apiman/manager/api/beans/apis/JacksonCyclicalSerialisationTest.java
  manager/api/core/src/main/java/io/apiman/manager/api/core/IStorage.java
  manager/api/es/src/main/java/io/apiman/manager/api/es/EsMarshalling.java
  manager/api/es/src/main/java/io/apiman/manager/api/es/EsStorage.java
  manager/api/export-import/src/main/java/io/apiman/manager/api/exportimport/OrgElementsEnum.java
  manager/api/export-import/src/main/java/io/apiman/manager/api/exportimport/json/JsonExportWriter.java
  manager/api/export-import/src/main/java/io/apiman/manager/api/exportimport/json/JsonImportReader.java
  manager/api/export-import/src/main/java/io/apiman/manager/api/exportimport/manager/LoggingDispatcher.java
  manager/api/export-import/src/main/java/io/apiman/manager/api/exportimport/manager/StorageExporter.java
  manager/api/export-import/src/main/java/io/apiman/manager/api/exportimport/manager/StorageImportDispatcher.java
  manager/api/export-import/src/main/java/io/apiman/manager/api/exportimport/read/IImportReaderDispatcher.java
  manager/api/export-import/src/main/java/io/apiman/manager/api/exportimport/write/IExportWriter.java
  manager/api/export-import/src/main/resources/io/apiman/manager/api/exportimport/i18n/messages.properties
  manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/JpaStorage.java
  manager/api/micro/pom.xml
  manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/OrganizationResourceImpl.java
  manager/api/war/tomcat8/pom.xml
  manager/test/api/pom.xml
  manager/test/api/src/main/java/io/apiman/manager/test/server/TestEsStorageWrapper.java
  manager/test/api/src/test/resources/test-plan-data/developers/008_getAllMatchingApiVersions.resttest
  manager/test/api/src/test/resources/test-plan-data/developers/012_getAllPublicApiVersions.resttest
  manager/test/api/src/test/resources/test-plan-data/export/creates-1/008.5_add-api-definition.resttest
  manager/test/api/src/test/resources/test-plan-data/export/export/001_export-1.resttest
  manager/test/api/src/test/resources/test-plan-data/export/export/003_export-2-download.resttest
  manager/test/api/src/test/resources/test-plan-data/export/export/004_export-3.resttest
  manager/test/api/src/test/resources/test-plan-data/export/export/005_exportDeveloper.resttest
  manager/test/api/src/test/resources/test-plan-data/import/001_import.resttest
  manager/test/api/src/test/resources/test-plan-data/import/002_import-again.resttest
  manager/test/api/src/test/resources/test-plan-data/import/003_import-with-developer.resttest
  manager/test/api/src/test/resources/test-plan-data/migrate/001_import-1.2.2.Final.resttest
  manager/test/api/src/test/resources/test-plan-data/migrate/002_export.resttest
  manager/test/api/src/test/resources/test-plans/developers-testPlan.xml
  manager/test/api/src/test/resources/test-plans/export-testPlan.xml
  manager/test/api/src/test/resources/test-plans/exportDeveloper-testPlan.xml
  parent/pom.xml
  test/common/src/main/java/io/apiman/test/common/es/EsTestUtil.java
  test/common/src/main/java/io/apiman/test/common/util/TestPlanRunner.java
Labels: bug

#1310 refactor(es): add logging to ESCacheStoreComponent
  gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsCacheStoreComponent.java
Labels: refactor

#1300 refactor: improved options parsing in components (stage 1)
  common/config/src/main/java/io/apiman/common/config/options/GenericOptionsParser.java
  common/config/src/main/java/io/apiman/common/config/options/Predicates.java
  common/config/src/main/java/io/apiman/common/config/options/TLSOptions.java
  common/config/src/main/java/io/apiman/common/config/options/exceptions/BadOptionConfigurationException.java
  common/es/src/main/java/io/apiman/common/es/util/AbstractEsComponent.java
  common/es/src/main/java/io/apiman/common/es/util/ApimanEsClientOptionsParser.java
  common/es/src/main/java/io/apiman/common/es/util/DefaultEsClientFactory.java
  common/plugin/pom.xml
  common/plugin/src/test/java/io/apiman/common/config/options/GenericOptionsParserTest.java
  gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/InMemoryCacheStoreComponent.java
  gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/InMemoryRateLimiterComponent.java
  gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/InMemoryRegistry.java
  gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsMetrics.java
Labels: refactor

#1315 build(deps): elasticsearch, hibernate, commons-io, mockito, Maven dependency plugin
  parent/pom.xml
Labels: dependency

#1325 test(test-common): TestPlanRunner retry up to 4 times on IOException
  test/common/src/main/java/io/apiman/test/common/util/TestPlanRunner.java
Labels: test

#1324 refactor(platform-vertx): improve error message when wrong buffer implementation used
  gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/connector/HttpConnector.java
  gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/io/VertxApimanBuffer.java
  gateway/platforms/vertx3/vertx3/src/main/resources/io/apiman/gateway/platforms/vertx3/i18n/messages.properties
Labels: refactor

#1351 docs(dev-guide): fix callouts and use Asciidoc-style code blocks
  docs/modules/ROOT/pages/development/Plugins.adoc
Labels: docs
