Repository apiman/apiman, pull requests merged in 2021-03, with the labels that each got.

#1015 Refactor: Allow to configure host for gateway testcontainer
  gateway/test/src/test/java/io/apiman/gateway/test/junit/vertx3/Vertx3GatewayEsServerFactory.java
  gateway/test/src/test/resources/vertx3/conf-es.json
Labels: enhancement

#1020 build(deps): bump Keycloak from 12.0.1 to 12.0.4
  pom.xml
Labels: dependency, java

#1019 build(deps): bump Infinispan from 8.1.9.Final to 8.2.12.Final
  pom.xml
Labels: dependency, java

#1027 build: Remove references to old maven repos
  pom.xml
Labels: build

#1029 build(deps): Bump core Maven plugins to latest versions
  pom.xml
Labels: build

#1034 build(deps): Bump Jandex from 2.0.2.Final to 2.2.3.Final
  pom.xml
Labels: dependency, java

#1045 fix(gateway-vertx): debug with java 9+
  distro/vertx/src/main/resources/overlay/apiman-gateway.sh
Labels: bug

#1047 fix: Set PolicyFailure error code if '0' before write
  gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPolicyFailureWriter.java
Labels: bug

#1074 refactor(es): improve readability of getOrDefault config checks
  common/es/src/main/java/io/apiman/common/es/util/AbstractEsComponent.java
  common/es/src/main/java/io/apiman/common/es/util/DefaultEsClientFactory.java
  common/es/src/main/java/io/apiman/common/es/util/LocalClientFactory.java
Labels: enhancement

#1075 feat(ui): validation for api definitions & user-friendly error modal
  manager/ui/war/plugins/api-manager/css/apiman.css
  manager/ui/war/plugins/api-manager/html/api/api-def.html
  manager/ui/war/plugins/api-manager/html/modals/errorModal.html
  manager/ui/war/plugins/api-manager/ts/api/api-def.ts
  manager/ui/war/plugins/api-manager/ts/modals.ts
Labels: enhancement
