Repository apiman/apiman, pull requests merged in 2022-05, with the labels that each got.

#1956 chore(deps): bump Vert.x and Netty
  parent/pom.xml
Labels: dependency, V: Apiman 3

#1961 build(deps): minor Java dependency update bundle
  parent/pom.xml
Labels: dependency, java, V: Apiman 3

#1990 build(deps): bump luxon, @toast-ui/editor-plugin-color-syntax, node-f…
  manager/ui/war/package.json
  manager/ui/war/yarn.lock
Labels: dependency, javascript, V: Apiman 3

#2004 bump(deps-dev): Cypress, glob, html-webpack-plugin, prettier, ts-load…
  manager/ui/war/gulpfileCI.js
  manager/ui/war/package.json
  manager/ui/war/yarn.lock
Labels: V: Apiman 3

#2008 build(deps): bump typescript from 4.5.3 to 4.6.4 and @types/*
  manager/ui/war/package.json
  manager/ui/war/yarn.lock
Labels: dependency, javascript, V: Apiman 3

#2012 fix(manager-api-war): handle comma-separated lists properly in `apiman.properties`
  gateway/platforms/war/src/main/java/io/apiman/gateway/platforms/war/WarEngineConfig.java
Labels: T: Bug, V: Apiman 3, C: Gateway

#2037 fix(manager): work around ES index creation race condition
  common/es/src/main/java/io/apiman/common/es/util/AbstractClientFactory.java
Labels: V: Apiman 3

#2041 build(gateway-platforms-vertx3): ensure Vert.x gateway can use JDBC registry
  gateway/platforms/vertx3/vertx3/pom.xml
Labels: V: Apiman 3

#2048 fix(manager-api-beans): add `@Type(type = "org.hibernate.type.TextType")` back for existing fields
  distro/data/src/main/resources/ddls/apiman_h2.ddl
  manager/api/beans/src/main/java/io/apiman/manager/api/beans/audit/AuditEntryBean.java
  manager/api/beans/src/main/java/io/apiman/manager/api/beans/gateways/GatewayBean.java
  manager/api/beans/src/main/java/io/apiman/manager/api/beans/policies/PolicyBean.java
  manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/ApimanH2Dialect.java
Labels: V: Apiman 3

#2050 fix(manager-api): fix image upload
  manager/api/war/tomcat8/src/main/webapp/WEB-INF/web.xml
  manager/api/war/wildfly8/src/main/webapp/WEB-INF/web.xml
Labels: V: Apiman 3

#2034 fix(ui): fix display of policy edit view
  manager/ui/war/plugins/api-manager/html/forms/edit-policy.html
Labels: V: Apiman 3

#2070 fix(manager-api): grant membership as non-admin user
  manager/api/rest-impl/src/main/java/io/apiman/manager/api/service/OrganizationService.java
  manager/test/api/src/test/resources/test-plan-data/members/auditing/001_activity.resttest
  manager/test/api/src/test/resources/test-plan-data/members/manage/004_grant-user1-api.resttest
  manager/test/api/src/test/resources/test-plan-data/members/manage/005_grant-user2-api.resttest
  manager/test/api/src/test/resources/test-plan-data/members/manage/006_get-members.resttest
  manager/test/api/src/test/resources/test-plan-data/members/manage/007_revoke-user2.resttest
  manager/test/api/src/test/resources/test-plan-data/members/manage/008_get-members.resttest
Labels: V: Apiman 3

#2072 fix(ui): restore "requires approval" functionality on devportal tab
  manager/ui/war/plugins/api-manager/html/api/api-devportal.html
  manager/ui/war/plugins/api-manager/ts/api/api-devportal.ts
Labels: V: Apiman 3
